export enum OpportunityStatus {
  SAVED = "SAVED",
  CONTACTING = "CONTACTING",
  APPLIED = "APPLIED",
  INTERVIEW = "INTERVIEW",
  REJECTED = "REJECTED",
  OFFER = "OFFER",
  GHOSTED = "GHOSTED",
}

export enum OpportunitySource {
  LINKEDIN_JOB = "LINKEDIN_JOB",
  LINKEDIN_POST = "LINKEDIN_POST",
  INSTAHYRE = "INSTAHYRE",
  NAUKRI = "NAUKRI",
  WELLFOUND = "WELLFOUND",
  GREENHOUSE = "GREENHOUSE",
  LEVER = "LEVER",
  WORKDAY = "WORKDAY",
  MANUAL = "MANUAL",
}

export enum ContactRole {
  HR = "HR",
  RECRUITER = "RECRUITER",
  EMPLOYEE = "EMPLOYEE",
  EM = "EM",
  CTO = "CTO",
  CEO = "CEO",
  FOUNDER = "FOUNDER",
}

export enum OutreachType {
  REFERRAL = "REFERRAL",
  LINKEDIN_DM = "LINKEDIN_DM",
  EMAIL = "EMAIL",
  WHATSAPP = "WHATSAPP",
  DIRECT_APPLY = "DIRECT_APPLY",
}

export enum OutreachStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  FOLLOWUP = "FOLLOWUP",
  RESPONDED = "RESPONDED",
  REJECTED = "REJECTED",
  REFERRAL_GIVEN = "REFERRAL_GIVEN",
  REPLIED = "REPLIED",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
}

export enum TemplateType {
  REFERRAL = "REFERRAL",
  COLD_EMAIL = "COLD_EMAIL",
  FOLLOWUP = "FOLLOWUP",
  LINKEDIN_DM = "LINKEDIN_DM",
}

export enum JobLevel {
    INTERN = "INTERN",
    ENTRY_LEVEL = "ENTRY_LEVEL",
    MID_LEVEL = "MID_LEVEL",
    SENIOR = "SENIOR",
    STAFF = "STAFF",
    PRINCIPAL = "PRINCIPAL",
    LEAD = "LEAD",
    MANAGER = "MANAGER",
    DIRECTOR = "DIRECTOR",
    VP = "VP",
    EXECUTIVE = "EXECUTIVE",
    OTHER = "OTHER",
}

export enum JobRole {
    SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER",
    FRONTEND_ENGINEER = "FRONTEND_ENGINEER",
    BACKEND_ENGINEER = "BACKEND_ENGINEER",
    FULLSTACK_ENGINEER = "FULLSTACK_ENGINEER",
    MOBILE_ENGINEER = "MOBILE_ENGINEER",
    DEVOPS_ENGINEER = "DEVOPS_ENGINEER",
    SITE_RELIABILITY_ENGINEER = "SITE_RELIABILITY_ENGINEER",
    PLATFORM_ENGINEER = "PLATFORM_ENGINEER",
    CLOUD_ENGINEER = "CLOUD_ENGINEER",
    DATA_ENGINEER = "DATA_ENGINEER",
    DATA_ANALYST = "DATA_ANALYST",
    DATA_SCIENTIST = "DATA_SCIENTIST",
    MACHINE_LEARNING_ENGINEER = "MACHINE_LEARNING_ENGINEER",
    AI_ENGINEER = "AI_ENGINEER",
    QA_ENGINEER = "QA_ENGINEER",
    SECURITY_ENGINEER = "SECURITY_ENGINEER",
    PRODUCT_MANAGER = "PRODUCT_MANAGER",
    PROJECT_MANAGER = "PROJECT_MANAGER",
    BUSINESS_ANALYST = "BUSINESS_ANALYST",
    SOLUTIONS_ENGINEER = "SOLUTIONS_ENGINEER",
    TECHNICAL_SUPPORT_ENGINEER = "TECHNICAL_SUPPORT_ENGINEER",
    OTHER = "OTHER",
}

export enum RequiredSkills {
  // Programming Languages
  JAVA = "JAVA",
  PYTHON = "PYTHON",
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  C = "C",
  CPP = "C++",
  CSHARP = "C#",
  GO = "GO",
  RUST = "RUST",
  KOTLIN = "KOTLIN",
  SWIFT = "SWIFT",
  PHP = "PHP",
  RUBY = "RUBY",
  SCALA = "SCALA",
  DART = "DART",
  R = "R",

  // Frontend
  HTML = "HTML",
  CSS = "CSS",
  SASS = "SASS",
  TAILWIND = "TAILWIND CSS",
  BOOTSTRAP = "BOOTSTRAP",
  REACT = "REACT.JS",
  NEXT = "NEXT.JS",
  ANGULAR = "ANGULAR",
  VUE = "VUE.JS",
  REDUX = "REDUX",
  MATERIAL_UI = "MATERIAL UI",

  // Backend Frameworks
  NODEJS = "NODE.JS",
  EXPRESS = "EXPRESS.JS",
  NESTJS = "NESTJS",
  DJANGO = "DJANGO",
  FLASK = "FLASK",
  FASTAPI = "FASTAPI",
  SPRING_BOOT = "SPRING BOOT",
  HIBERNATE = "HIBERNATE",
  ASP_NET = "ASP.NET",
  LARAVEL = "LARAVEL",
  RUBY_ON_RAILS = "RUBY ON RAILS",

  // Databases
  MYSQL = "MYSQL",
  POSTGRESQL = "POSTGRESQL",
  MONGODB = "MONGODB",
  SQLITE = "SQLITE",
  REDIS = "REDIS",
  ELASTICSEARCH = "ELASTICSEARCH",
  CASSANDRA = "CASSANDRA",
  DYNAMODB = "DYNAMODB",
  FIREBASE = "FIREBASE",

  // Cloud Platforms
  AWS = "AWS",
  AZURE = "AZURE",
  GCP = "GCP",
  HEROKU = "HEROKU",
  VERCEL = "VERCEL",
  NETLIFY = "NETLIFY",

  // DevOps & Infrastructure
  DOCKER = "DOCKER",
  KUBERNETES = "KUBERNETES",
  JENKINS = "JENKINS",
  TERRAFORM = "TERRAFORM",
  ANSIBLE = "ANSIBLE",
  GITHUB_ACTIONS = "GITHUB ACTIONS",
  CI_CD = "CI/CD",
  NGINX = "NGINX",
  LINUX = "LINUX",

  // Mobile Development
  REACT_NATIVE = "REACT NATIVE",
  FLUTTER = "FLUTTER",
  ANDROID = "ANDROID",
  IOS = "IOS",

  // AI / ML / Data Science
  MACHINE_LEARNING = "MACHINE LEARNING",
  DEEP_LEARNING = "DEEP LEARNING",
  TENSORFLOW = "TENSORFLOW",
  PYTORCH = "PYTORCH",
  SCIKIT_LEARN = "SCIKIT LEARN",
  NLP = "NLP",
  COMPUTER_VISION = "COMPUTER VISION",
  GENAI = "GENERATIVE AI",
  LLM = "LLM",
  LANGCHAIN = "LANGCHAIN",
  OPENAI = "OPENAI API",
  GEMINI = "GEMINI API",

  // Data Engineering
  APACHE_SPARK = "APACHE SPARK",
  HADOOP = "HADOOP",
  AIRFLOW = "AIRFLOW",
  KAFKA = "KAFKA",
  ETL = "ETL",

  // Testing
  JEST = "JEST",
  CYPRESS = "CYPRESS",
  SELENIUM = "SELENIUM",
  PLAYWRIGHT = "PLAYWRIGHT",
  JUNIT = "JUNIT",
  PYTEST = "PYTEST",

  // Version Control & Tools
  GIT = "GIT",
  GITHUB = "GITHUB",
  GITLAB = "GITLAB",
  POSTMAN = "POSTMAN",
  SWAGGER = "SWAGGER",

  // Concepts
  REST_API = "REST API",
  GRAPHQL = "GRAPHQL",
  MICROSERVICES = "MICROSERVICES",
  SYSTEM_DESIGN = "SYSTEM DESIGN",
  OOPS = "OOPS",
  DSA = "DATA STRUCTURES & ALGORITHMS",
  DESIGN_PATTERNS = "DESIGN PATTERNS",
  AGILE = "AGILE",
}