// constants.js

export const JOB_ROLES = [
  "SOFTWARE_ENGINEER",
  "FRONTEND_ENGINEER",
  "BACKEND_ENGINEER",
  "FULLSTACK_ENGINEER",
  "MOBILE_ENGINEER",
  "DEVOPS_ENGINEER",
  "DATA_ENGINEER",
  "DATA_SCIENTIST",
  "MACHINE_LEARNING_ENGINEER",
  "AI_ENGINEER",
  "PRODUCT_MANAGER",
  "OTHER",
];

export const JOB_LEVELS = [
  "INTERN",
  "ENTRY_LEVEL",
  "MID_LEVEL",
  "SENIOR",
  "STAFF",
  "PRINCIPAL",
  "LEAD",
  "MANAGER",
  "DIRECTOR",
  "VP",
  "EXECUTIVE",
  "OTHER",
];

export const OPPORTUNITY_SOURCES = [
  "LINKEDIN_JOB",
  "LINKEDIN_POST",
  "INSTAHYRE",
  "NAUKRI",
  "WELLFOUND",
  "GREENHOUSE",
  "LEVER",
  "WORKDAY",
  "MANUAL",
];

export const OPPORTUNITY_STATUS = [
  "SAVED",
  "CONTACTING",
  "APPLIED",
  "INTERVIEW",
  "REJECTED",
  "OFFER",
  "GHOSTED",
];